export const projects = [
  {
    title: 'Favel',
    description:"A social network platform that allows sending and sharing posts, as well as importing of other sources of posts(Github, Twitter, etc.).  ",
      image: '/images/1.png',
      tags: ['Django RESTframwork', 'Heroku', 'Bootstrap'],
    source: 'https://github.com/shola1y',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Booker',
    description:"A Peer-to-Peer booksharing android app.",
    image: '/images/2.png',
    tags: ['Java', 'Android studio', 'Firebase'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'Healthwich',
    description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
      image: '/images/3.png',
      tags: ['Django', 'Heroku', 'Firebase'],
    source: 'https://github.com/shola1y/seekwent',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'Seekwent',
    description: "A single page application to help me choose where to travel to next and documenting my past destinations",
    image: '/images/4.jpg',
    tags: ['React', 'Next.js', 'Firebase'],
    source: 'https://github.com/shola1y/seekwent',
    visit: 'https://github.com/shola1y/seekwent',
    id: 3,
  },
  {
    title: 'Personal Website2.0',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['React', 'Tailwind CSS', 'Vercel'],
    source: 'https://github.com/shola1y/laly',
    visit: 'https://sholaomotosho.vercel.app',
    id: 4,
  },
  {
    title: 'Personal Website1.0',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/6.png',
    tags: ['React', 'Tailwind CSS', 'Vercel'],
    source: 'https://github.com/shola1y/',
    visit: 'https://sholaomotosho.vercel.app',
    id: 5,
  },
  {
    title: 'Shopfind',
    description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
    image: '/images/4.jpg',
    tags: ['GeoDjango', 'PostgreSQL','Docker'],
    source: 'https://google.com',
    visit: 'https://github.com/shola1y/Shopfind',
    id: 6,
  },
  {
    title: 'Lunar Landing',
    description: "A Trained Agent which learns to land on unstable terrain using Reinforcement learning tools",
    image: '/images/8.png',
    tags: ['Python', 'Jupyter Notebook'],
    source: 'https://github.com/shola1y/Lunar-Landing-Reinforcement-Learning-/tree/master/Coursera_Reinforcement_Learning-master',
    visit: 'https://github.com/shola1y/Lunar-Landing-Reinforcement-Learning-/tree/master/Coursera_Reinforcement_Learning-master',
    id: 7,
  }
];

export const TimeLineData = [
  { year: 2017, text: 'Started computer science degree', },
  
  { year: 2019, text: 'Worked as a freelance developer', },
  { year: 2020, text: 'completed IT internship', },
  { year: 2021, text: 'Finished University coursework and shared projects with the world', },
];